# Generated by Django 4.2 on 2024-05-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_products_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='HomeData',
        ),
    ]
