# Generated by Django 4.2 on 2024-05-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_womendata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WomenData',
        ),
    ]
